version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    container_name: mongodb
  reading-is-good:
    image: reading-is-good
    container_name: reading-is-good
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongodb

    links:
      - mongodb