version: '3.8'
services:
  backend:
    container_name: "readinisgood-service"
    restart: 'always'
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        JAR_FILE: reading-is-good.jar
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongodb
  mongodb:
    container_name: "readinisgood-db"
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
volumes:
  data: { }
networks:
  default:
    name: mongo_network