version: '3.8'
services:
  backend:
    container_name: "restapi"
    restart: 'always'
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        JAR_FILE: readingisgood.jar
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongodb
  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin1234
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: { }
networks:
  default:
    name: mongo_network